name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-pip openjdk-17-jdk unzip zip libffi-dev libssl-dev
          pip install cython virtualenv buildozer

      - name: Build with Buildozer
        run: |
          buildozer init
          buildozer -v android debug
